[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "paleo-emu"
version = "2025.09.25"
description = "A project for paleo-environmental modeling."
license = { text = "MIT" }
readme = "README.md"
homepage = "https://github.com/paleo-emu-model/paleo-emu"
repository = "https://github.com/paleo-emu-model/paleo-emu"
keywords = ["paleo", "environment", "modeling"]

[tool.hatch.version]
path = "paleo_emu/__init__.py"


[tool.hatch.build.targets.sdist]
include = ["README.md", "LICENSE"]

[tool.hatch.build.targets.wheel]
packages = ["paleo_emu"]
