variables:
  - "tas"
  - "pr"

# training data file paths and names

emulators: "highmod_ice"

# training data file paths and names
training_file_path: "examples/training_data/"
X_input: "training_data_highmodice_temp_formatted.res"
Y_output: "training_data_highmodice_temp_formatted.nc"


# save log files path
log_path: "examples/logs/"
output_dir: "examples/outputs/"


forcing_data:
  file_path: "examples/forcing_data/"
  rcp85.1:
    forcing_input: "Paleo_forcings_2Ma_xin.res"


# configuration of parameters for emulator training
PCA_config:
  n_components: 5
  pca_variance_ratio: 0.99
  
VAE_config:
  latent_dim: 1024   # 可选: 32,64,128,256,512,1024
  epochs: 80
  learning_rate: 1e-4
  batch_size: 128
  kl_weight: 0.1


# configurations for regressors.
# best hyperparameters are chosen based on
# -2. encoder type
GPR_config:
  #NEED to optimize there hp
  PCA:
    kernel: "RBF_White"
    length_scales: [233.2825891498896, 0.0022671649797259587, 41.72075091907251, 58.57768264765239, 182.12070551134408]
    noise_level: 0.0001
    nu: 1.5
    nugget_value: 0.00012474886011940795
    constant_value: 0.06354351729633832
    n_restarts_optimizer: 12
  VAE:
    kernel: "RBF_White"
    nugget_value: 1e-6
    length_scales: [1.0]
    alpha: 1e-10
    normalize_y: true
  old_R_emulator_hyperparameters: 
    nkeep: 20.0
    hp_values: [1.02978659, 1.28309734, 0.44338942, 2.71906639, 0.84986604, 0.10781086297849862]


LGBM_config:
  PCA:
    num_leaves: 164
    max_depth: 3
    learning_rate: 0.03995250113480687
    n_estimators: 645
    subsample: 0.4032131424792672
    colsample_bytree: 0.8371757523192892
    min_child_samples: 5
    random_state: 42
    n_jobs: 1
  VAE:
    num_leaves: 164
    max_depth: 3
    learning_rate: 0.03995250113480687
    n_estimators: 645
    subsample: 0.4032131424792672
    colsample_bytree: 0.8371757523192892
    min_child_samples: 5
    random_state: 42
    n_jobs: 1

