# this file should contains the following configurations:
# 1.1 input variable names
# 1.2 input path and file names for training data
# 1.3 output path for logs and trained emulators
# 2.1 encoder type 
# 2.2 encoder configurations
# 2.2.2 encoder hyperparameters configurations
# 2.3 regressor type
# 2.4 regressor configurations
# 2.4.2 regressor hyperparameters configurations
# 3. the name of emulator


model_run_name: "test_18Nov"

variables:
  - "tas"
  - "pr"

# training data file paths and names
training_file_path: "examples/training_data/"
X_input: "training_data_lowmodice_temp_formatted.res"
Y_input: "training_data_lowmodice_temp_formatted.nc"

# training_test.yaml
save_path: examples/
save_pipeline: false

<<<<<<< Updated upstream
# save log files path
log_path: "examples/logs/"
output_dir: "examples/outputs/"


forcing_data:
  file_path: "examples/forcing_data/"
  rcp85.1:
    forcing_input: "emul_inputs_RCP85.67.res"
=======
# forcing data paths
forcing_data_folder: "examples/forcing_data/"
forcing_input: "RCP85.1" #if empty use all forcings
>>>>>>> Stashed changes


# configuration of parameters for emulator training
encoder_config:
  encoder_type: PCA
  n_components: 5
  pca_variance_ratio: 0.99
  
# configurations for regressors.
regressor_config:
  regressor_type: GPR
  kernel: "RBF_White"
  length_scales: [233.2825891498896, 0.0022671649797259587, 41.72075091907251, 58.57768264765239, 182.12070551134408]
  noise_level: 0.0001
  nu: 1.5
  nugget_value: 0.000124748860119
  constant_value: 0.06354351729633832
  n_restarts_optimizer: 12